spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spread?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: service
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver